Add unit tests for `utils.ts`
GrapesJS/cli pull request #294
Opened 2024-09-02 12:10 UTC by mohamedsalem401

Add configuration for jest testing
Add unit tests for all functions in the utils.ts file
One commented test that should be uncommented or replaced

2024-09-02 16:44 UTC, danstarns requested changes
Looks great, can we add into CI?

2024-09-02 16:51 UTC, danstarns commented on test/utils.spec.ts
> +    // TODO: Fix this test as we can't mock the process.cwd
How come we can't mock?

2024-09-02 17:07 UTC, mohamedsalem401 commented on test/utils.spec.ts
> +    // TODO: Fix this test as we can't mock the process.cwd
I couldn't figure out the so.
I think it's related to the following issue in the Jest GitHub repository:
[Jest globals differ from Node globals
](https://github.com/jestjs/jest/issues/2549)


Also take a look at:
https://github.com/jestjs/jest/issues/5146

2024-09-02 17:08 UTC, mohamedsalem401 commented
> Looks great, can we add into CI?
I'll work on that

2024-09-02 17:33 UTC, mohamedsalem401 commented on test/utils.spec.ts
> +    // TODO: Fix this test as we can't mock the process.cwd
@danstarns  
I've changed the test, it's currently using the same logic as the actual function itself, so it should always pass, but at least we are ensuring that the function is correctly implemented and accessible in our test environment.

```ts
describe('rootResolve', () => {
    it('should resolve a relative path to an absolute path', () => {
        const result = rootResolve('src/index.js');

        expect(result).toBe(path.join(process.cwd(), 'src/index.js'));
    });
});
```

2024-09-05 11:12 UTC, artf approved these changes
🚀

2024-09-05 16:33 UTC, merged